### ISSUE TITLE
NECB QAQC errors for SmallOffice, RetailStripMall, and Outpatient

### ISSUE THREAD

**Issue by padmassun** [canmet-energy/btap_tasks#67]
```
[12:12:51.239511 ERROR] undefined method `*' for nil:NilClass 
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/openstudio-standards-71ce2d1a2e21/lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb:358:in `create_base_qaqc' 
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/openstudio-standards-71ce2d1a2e21/lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb:44:in `init_qaqc' 
```
Line 358: `    doors.size > 0 ? sky_cond_weight = qaqc[:envelope][:skylights_average_conductance_w_per_m2_k] * qaqc[:envelope][:skylights_area_m2] : sky_cond_weight = 0
`

**Comment by padmassun** [comment]
Completed
