### ISSUE TITLE
Fix HVAC Tests that use runmanager

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#68]
@khaddad Apparently the Runmanger methods have been removed by NREL.. so the only way to run a model is to use the new methods..and without a server..it will run one test at a time only. 

This will make testing the necb systems test very long.. so I am breaking the tests into separate files 1 to 7 to speed up things and let CircleCI divide it up.

**Comment by phylroy** [comment]
All tests have now been converted to individual tests for each system
test_necb_hvac_system_1.rb
test_necb_hvac_system_2.rb
test_necb_hvac_system_3.rb
test_necb_hvac_system_4.rb
test_necb_hvac_system_5.rb
test_necb_hvac_system_6.rb
test_necb_hvac_system_7.rb

This has been added to the circleci run tasks.

**Comment by phylroy** [comment]
There was an error for system 5 as seen below. @khaddad  Could you have a look? Looks like something is overheating in the test. 

```
/usr/local/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) -Ilib:test /home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb
Testing started at 5:55 PM ...
DEVELOPERS OF OPENSTUDIO-STANDARDS: Requiring code directly instead of using installed gem.  This avoids having to run rake install every time you make a change.
Started with run options --seed 55407

***************************************sys5_Boiler~NaturalGas_ChillerType~Scroll_MuaCoolingType~DX*******************************************************
[openstudio.EpwFile] <0> Successive data points (1999-Jan-31 to 2004-Feb-01, ending on line 753) are greater than 1 day apart in EPW file '/home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.epw'. Data will be treated as typical (TMY)
[openstudio.setFileExtension] <0> Path p, '/home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.ddy', has an unexpected file extension. Was expecting 'idf'.
[openstudio.setFileExtension] <0> Path p, '/home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.ddy', has an unexpected file extension. Was expecting 'idf'.
INFO: BTAP::Environment::WeatherFile::set_weather
INFO: Set model "Small Office" to weather file /home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.epw.
INFO: Setting water main temperatures via parsing of STAT file.
INFO: SiteWaterMainsTemperature.AnnualAverageOutdoorAirTemperature = 9.058333333333334.
INFO: SiteWaterMainsTemperature.MaximumDifferenceInMonthlyAverageOutdoorAirTemperatures = 28.299999999999997.
INFO: Adding design day 'Toronto Pearson Intl AP Ann Clg .4% Condns DB=>MWB'.
INFO: Adding design day 'Toronto Pearson Intl AP Ann Htg 99.6% Condns DB'.
INFO: Adding design day 'Toronto Pearson Intl AP Ann Clg .4% Condns WB=>MDB'.
[openstudio.model.ChillerElectricEIR] <0> Cannot set condenserType to 'WaterCooled', chiller 'Chiller Electric EIR 1' is not connected to a secondaryPlantLoop
[openstudio.model.ChillerElectricEIR] <0> Cannot set condenserType to 'WaterCooled', chiller 'Chiller Electric EIR 2' is not connected to a secondaryPlantLoop
[openstudio.setFileExtension] <0> Path p, '/home/osdev/openstudio-standards/test/necb/output/test_necb_system_5/sys5_Boiler~NaturalGas_ChillerType~Scroll_MuaCoolingType~DX.hvacrb', has an unexpected file extension. Was expecting 'osm'.
[openstudio.energyplus.ForwardTranslator] <0> OS_ProgramControl is not currently translated
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff 1 from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional 1 from field 1, but that object cannot be located.
"/usr/Ruby/../bin/openstudio" run -w "/home/osdev/openstudio-standards/test/necb/output/test_necb_system_5/sys5_Boiler~NaturalGas_ChillerType~Scroll_MuaCoolingType~DX/sizing/SizingRun1/in.osw"
found sizing run /home/osdev/openstudio-standards/test/necb/output/test_necb_system_5/sys5_Boiler~NaturalGas_ChillerType~Scroll_MuaCoolingType~DX/sizing/SizingRun1
[openstudio.standards.Fan] <0> For Fan Constant Volume 1, there is no greater nominal HP.  Use the efficiency of the largest motor category.
[openstudio.EpwFile] <0> Successive data points (1999-Jan-31 to 2004-Feb-01, ending on line 753) are greater than 1 day apart in EPW file '/home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.epw'. Data will be treated as typical (TMY)
[openstudio.setFileExtension] <0> Path p, '/home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.ddy', has an unexpected file extension. Was expecting 'idf'.
[openstudio.setFileExtension] <0> Path p, '/home/osdev/openstudio-standards/data/weather/CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.ddy', has an unexpected file extension. Was expecting 'idf'.
[openstudio.standards.Fan] <0> For Fan Constant Volume 1, there is no greater nominal HP.  Use the efficiency of the largest motor category.
[openstudio.standards.CoolingTower] <0> For Cooling Tower Single Speed 1, cannot find heat rejection properties, cannot apply standard efficiencies or curves.
[openstudio.energyplus.ForwardTranslator] <0> OS_ProgramControl is not currently translated
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff 1 from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional 1 from field 1, but that object cannot be located.
"/usr/Ruby/../bin/openstudio" run -w "/home/osdev/openstudio-standards/test/necb/output/test_necb_system_5/sys5_Boiler~NaturalGas_ChillerType~Scroll_MuaCoolingType~DX//in.osw"
[17:56:22.273572 WARN] EnergyPlus returned a non-zero exit code. Check the stdout-energyplus log.
[17:56:22.274016 ERROR] :/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb failed with EnergyPlus Terminated with a Fatal Error. Check eplusout.err log., :/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb:146:in `call_energyplus'
:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_energyplus.rb:44:in `perform'
:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'
:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'
:/openstudio_cli.rb:821:in `execute'
:/openstudio_cli.rb:620:in `execute'
:/openstudio_cli.rb:1547:in `<main>'
eval:85:in `eval'
eval:85:in `require_embedded_absolute'
eval:70:in `block in require'
eval:64:in `each'
eval:64:in `require'
eval:2:in `<main>'
[17:56:22.276579 ERROR] Found error in state 'simulation' with message [":/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb failed with EnergyPlus Terminated with a Fatal Error. Check eplusout.err log., :/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb:146:in `call_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_energyplus.rb:44:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'\n:/openstudio_cli.rb:821:in `execute'\n:/openstudio_cli.rb:620:in `execute'\n:/openstudio_cli.rb:1547:in `<main>'\neval:85:in `eval'\neval:85:in `require_embedded_absolute'\neval:70:in `block in require'\neval:64:in `each'\neval:64:in `require'\neval:2:in `<main>'::/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb:165:in `rescue in call_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb:172:in `call_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_energyplus.rb:44:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'\n:/openstudio_cli.rb:821:in `execute'\n:/openstudio_cli.rb:620:in `execute'\n:/openstudio_cli.rb:1547:in `<main>'\neval:85:in `eval'\neval:85:in `require_embedded_absolute'\neval:70:in `block in require'\neval:64:in `each'\neval:64:in `require'\neval:2:in `<main>'"]}
[openstudio.model.Model] <1> The run failed with the following severe or fatal errors: Plant temperatures are getting far too hot, check controls and relative loads and capacities   Environment=RUN PERIOD 1, at Simulation time=09/08 14:34 - 14:36  PlantLoop Name (SupplySide)= HOT WATER LOOP  PlantLoop Setpoint Temperature=60.0 {C}  PlantLoop Inlet Node (SupplySide) does not have a Setpoint.  PlantLoop Inlet Node (DemandSide) does not have a Setpoint.  PlantLoop Outlet Node (SupplySide) has a Setpoint.  PlantLoop Outlet Node (DemandSide) does not have a Setpoint.  PlantLoop Outlet Node (SupplySide) "NODE 7" has temperature=300.0 {C}  PlantLoop  Inlet Node (SupplySide) "NODE 6" has temperature=300.0 {C}  PlantLoop Minimum Temperature=0.0 {C}  PlantLoop Maximum Temperature=100.0 {C}  PlantLoop Flow Request (SupplySide)=0.0 {kg/s}  PlantLoop Flow Request (DemandSide)=0.1 {kg/s}  PlantLoop Node (SupplySide) "NODE 7" has mass flow rate =0.1 {kg/s}  PlantLoop PumpHeat (SupplySide)=30.3 {W}  PlantLoop PumpHeat (DemandSide)=0.0 {W}  PlantLoop Cooling Demand=128557.3 {W}  PlantLoop Heating Demand=0.0 {W}  PlantLoop Demand not Dispatched=0.0 {W}  PlantLoop Unmet Demand=-128557.3 {W}  PlantLoop Capacity=77308.5 {W}  PlantLoop Capacity (SupplySide)=77308.5 {W}  PlantLoop Capacity (DemandSide)=0.0 {W}  PlantLoop Operation Scheme=HOT WATER LOOP OPERATION SCHEMES  PlantLoop Operation Dispatched Load = 0.0 {W}  PlantLoop Operation Dispatched Load (SupplySide)= 0.0 {W}  PlantLoop Operation Dispatched Load (DemandSide)= 0.0 {W}  Branches on the Loop.  Demand Branches:    HOT WATER LOOP DEMAND INLET BRANCH      Components on Branch:        PIPE:ADIABATIC:HOT WATER LOOP DEMAND INLET PIPE    HOT WATER LOOP DEMAND BRANCH 1      Components on Branch:        COIL:HEATING:WATER:COIL HEATING WATER 1    HOT WATER LOOP DEMAND BRANCH 2      Components on Branch:        COIL:HEATING:WATER:COIL HEATING WATER 2    HOT WATER LOOP DEMAND BRANCH 3      Components on Branch:        COIL:HEATING:WATER:COIL HEATING WATER 3    HOT WATER LOOP DEMAND BRANCH 4      Components on Branch:        COIL:HEATING:WATER:COIL HEATING WATER 4    HOT WATER LOOP DEMAND BRANCH 5      Components on Branch:        COIL:HEATING:WATER:COIL HEATING WATER 5    HOT WATER LOOP DEMAND BYPASS BRANCH      Components on Branch:        PIPE:ADIABATIC:HOT WATER LOOP DEMAND BYPASS PIPE    HOT WATER LOOP DEMAND OUTLET BRANCH      Components on Branch:        PIPE:ADIABATIC:HOT WATER LOOP DEMAND OUTLET PIPE  Supply Branches:    HOT WATER LOOP SUPPLY INLET BRANCH      Components on Branch:        PUMP:VARIABLESPEED:PUMP VARIABLE SPEED 1    HOT WATER LOOP SUPPLY BRANCH 1      Components on Branch:        BOILER:HOTWATER:PRIMARY BOILER 264KBTU/HR 0.85 AFUE    HOT WATER LOOP SUPPLY BRANCH 2      Components on Branch:        BOILER:HOTWATER:SECONDARY BOILER 0KBTU/HR 0.85 AFUE    HOT WATER LOOP SUPPLY BRANCH 3      Components on Branch:        PIPE:ADIABATIC:PIPE ADIABATIC 1    HOT WATER LOOP SUPPLY OUTLET BRANCH      Components on Branch:        PIPE:ADIABATIC:PIPE ADIABATIC 2  *************************  Possible things to look for to correct this problem are:    Capacity, Operation Scheme, Mass flow problems, Pump Heat building up over time.    Try a shorter runperiod to stop before it fatals and look at      lots of node time series data to see what is going wrong.    If this is happening during Warmup, you can use Output:Diagnostics,ReportDuringWarmup;    This is detected at the loop level, but the typical problems are in the components.\nCheckForRunawayPlantTemps: Simulation terminated because of run away plant temperatures, too hot

Minitest::Assertion: Failure in Standards for sys5_Boiler~NaturalGas_ChillerType~Scroll_MuaCoolingType~DX.
Expected: true
  Actual: false
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:72:in `block (4 levels) in test_system_5'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:51:in `each'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:51:in `block (3 levels) in test_system_5'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:50:in `each'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:50:in `block (2 levels) in test_system_5'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:49:in `each'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:49:in `block in test_system_5'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:47:in `each'
/home/osdev/openstudio-standards/test/necb/test_necb_hvac_system_5.rb:47:in `test_system_5'
Finished in 79.98067s
1 tests, 2 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/osdev/openstudio-standards/coverage. 3738 / 31141 LOC (12.0%) covered.

Process finished with exit code 1
```

**Comment by phylroy** [comment]
New branch for this task is nrcan_68
