### ISSUE TITLE
Fix error for BTAPResults with hourly_data enabled

### ISSUE THREAD

**Issue by padmassun** [canmet-energy/btap_tasks#72]
### Error log from OS-Server 2.4.3

```
[13:16:34.076826 ERROR] can't convert nil into an exact number 
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/time/calculations.rb:226:in `-' 
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/time/calculations.rb:226:in `minus_with_duration' 
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/time/calculations.rb:237:in `minus_with_coercion' 
/mnt/openstudio/analysis_1612ebf5-5a4f-42dc-b533-5b95517a1a5b/measures/BTAPResults/measure.rb:286:in `block in runHourlyReports' 
/mnt/openstudio/analysis_1612ebf5-5a4f-42dc-b533-5b95517a1a5b/measures/BTAPResults/measure.rb:243:in `each' 
/mnt/openstudio/analysis_1612ebf5-5a4f-42dc-b533-5b95517a1a5b/measures/BTAPResults/measure.rb:243:in `each_with_index' 
/mnt/openstudio/analysis_1612ebf5-5a4f-42dc-b533-5b95517a1a5b/measures/BTAPResults/measure.rb:243:in `runHourlyReports' 
/mnt/openstudio/analysis_1612ebf5-5a4f-42dc-b533-5b95517a1a5b/measures/BTAPResults/measure.rb:954:in `run' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/measure.rb:471:in `apply_measure' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/measure.rb:74:in `block in apply_measures' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/measure.rb:32:in `each_index' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/measure.rb:32:in `apply_measures' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_reporting_measures.rb:85:in `perform' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step' 
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run' 
/opt/openstudio/server/app/workers/run_simulate_data_point.rb:176:in `block in perform' 
/opt/openstudio/server/app/workers/run_simulate_data_point.rb:170:in `open' 
/opt/openstudio/server/app/workers/run_simulate_data_point.rb:170:in `perform' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/performable_method.rb:26:in `perform' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run' 
/usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout' 
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call' 
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run' 
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start' 
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in ' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:137:in `run' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:125:in `block in run_process' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/application.rb:270:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/application.rb:270:in `block in start_proc' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/application.rb:279:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/application.rb:279:in `start_proc' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/application.rb:300:in `start' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/controller.rb:59:in `run' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons.rb:197:in `block in run_proc' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/cmdline.rb:92:in `call' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons/cmdline.rb:92:in `catch_exceptions' 
/usr/local/lib/ruby/gems/2.2.0/gems/daemons-1.2.6/lib/daemons.rb:196:in `run_proc' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:123:in `run_process' 
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.5/lib/delayed/command.rb:98:in `daemonize' 
/opt/openstudio/server/bin/delayed_job:6:in `
' 
```

**Comment by padmassun** [comment]
@phylroy 
There were some issues with the master branch on Circle CI tests due to `nrel/openstusio:2.4.3` image not being found. which was resolved
https://github.com/canmet-energy/btap/commit/eef065ba8176a8ddb0961994cc34ecde776711bc
https://github.com/canmet-energy/btap/commit/65e3f334e5c2670c229b65df03f558d050d4ed88

Otherwise, waiting for merge
